version: '3'

services:

  cloud:
    build: 
      context: ./cloud
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

  nginx:
    image: nginx:latest
    volumes:
      - "./load-balancer/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 9999:9999
  
  local:
    build: 
      context: ./local
      dockerfile: Dockerfile
    ports:
      - "8000:5173"
    volumes:
      - ./local/src:/home/node/app/src
      - ./local/static:/home/node/app/static
      - ./local/vite.config.js:/home/node/app/vite.config.js
      - ./local/tailwind.config.cjs:/home/node/app/tailwind.config.cjs
      - ./local/postcss.config.cjs:/home/node/app/postcss.config.cjs
      - ./local/svelte.config.js:/home/node/app/svelte.config.js
    command: "npm run dev -- --host"
    environment:
      - PORT=5173
      - HOST=0.0.0.0